### ISSUE TITLE
On-chain zipped NFT

### ISSUE THREAD

**Issue by Cyanoure** [merklejerk/zipped-contracts#3]
Good evening, morning, afternoon or whatever the time is.
I'm new in Solidity development, I don't fully understand how does this work.
I'm contributing on an ERC721A on-chain NFT project, the HTML source code is stored in the contract, but I would like to move the code of the html, json and tokenURI generator (it makes a base64 datauri from the json) to a zipped contract. Is that possible?
Could someone help me out with an example or some other tips?
Also, it's the first time using Fountry, I'm learning it :D
I'm stuck at calling the zipped contract from the `tokenURI` function. I can't call the zipped contract with delegatecall because it says `Function cannot be declared as view because this expression (potentially) modifies the state.`
Also I'm not sure if I'm doing the zipped contract right. I'll test it later with other methods if it works at all.

**Comment by merklejerk** [comment]
Yes, it should be possible. Often you can just remove the `view` modifier from the `tokenURI()` function. You might have to modify your `ERC721` interface, or manually re-cast it, for tests, etc, to pass. But for most off-chain callers, it's all the same (they won't be using your ABI anyway).

If you really don't want to modify interfaces, another option is to hide the state-modifying logic from the compiler with a hack like:

```solidity
function tokenURI() external view {
    __forwardToZipped(ZIPPED);
}

function __forwardToZipped(address zipped) private view {
    function () fwd = __forwardToZippedNonView;
    function () view vfwd;
    assembly ("memory-safe") { vfwd := fwd }
    vfwd();
}

function  __forwardToZippedNonView(address zipped) private {
    assembly ("memory-safe") {
        calldatacopy(0x00, 0x00, calldatasize())
        let s := delegatecall(gas(), zipped, 0x00, calldatasize(), 0x00, 0x00)
        returndatacopy(0x00, 0x00, returndatasize())
        if iszero(s) {
            revert(0x00, returndatasize())
        }
        return(0x00, returndatasize())
    }
}
````

This is actually the trick used by wrapper contracts deployed by [bytecode.zip](https://bytecode.zip).

**Comment by Cyanoure** [comment]
I appreciate your help, thank you.
If I use my own function to generate the tokenURI, then I'm going to use it in the `tokenURI` function, does the visibility of my function have to match with the zipped contract?

Another question,
If I test the zipped contract with `interface` in the deploy script as like in the sample `DeployZCall.s.sol` and it works, does that mean I did everything right and my deployed zipped contract is working?

**Comment by merklejerk** [comment]
The answer is complicated due to how `view` is enforced in different calling contexts. When calling a `view` function from another contract, it will be enforced and any state-modifying operations (such as a self-extraction) will cause a revert. If, however, called directly by an EOA via `eth_call` (which is how `tokenURI()` is usually used), then the `view` modifier is ignored and will not be enforced.

I'm assuming you're trying to do something like this...?

```solidity
interface IZIPPED {
    function tokenURI() external view returns (string memory);
}

contract ERC721 {
    function tokenURI() external view returns (string memory) {
        return IZIPPED(zippedAddress).tokenURI();
    }
}
```

This will compile but revert because the `view` modifier on `IZIPPED.tokenURI()` will be enforced by the call inside `ERC721.tokenURI()`. If you drop `view` from just `IZIPPED`, it will not compile (unless you apply the assembly trick I mentioned earlier) because the compiler will not let you call a non-`view` function from a `view` function. If you drop `view` from both it will compile and succeed.

As for testing in the deployment in the deploy script, if you've inspected the output and it looks correct, then yes, it's probably fine. You could also use `forge cast` to call the deployed contract from the command line and inspect its results.

**Comment by merklejerk** [comment]
Or by visibility did you mean `external` vs `public`? You can mix those however you want.

**Comment by Cyanoure** [comment]
> Or by visibility did you mean `external` vs `public`? You can mix those however you want.

Yes, `external` vs `public`.
Sorry for misunderstanding. 😅

I've made a `test` function for easy testing that returns a `string`, but with `cast` it only returned a single `0x`. :(

I'm trying not to send the exact source code due to NDA.
This is how my project looks like:

`src/MyTokenGenerator.sol`
```solidity
...
contract MyTokenGenerator {
    ...
    function generateURI(
        string memory _previewBaseURI,
        uint256 _tokenId,
        bool _someCustomProperty
    ) external view returns (string memory) {
        return "Some generated base64 URI.";
    }
}
```

`script/deploy.sol`
```solidity
...
import "zipped-contracts/script/ZDeployBase.sol";
import "../src/MyTokenGenerator.sol";

contract Deploy is ZDeployBase {
    function run() external {
        Z z = _getOrDeployZ();
        vm.broadcast(vm.envUint('DEPLOYER_KEY'));
        _zcallDeploy(
            type(MyTokenGenerator).creationCode
        , z);
    }

    function test() external view returns (string memory) {
        return "this is a test";
    }
}
```

`.env`
```env
DEPLOYER_KEY=my_test_private_key
```

Then I deployed with this command:
```sh
forge script script/deploy.sol:Deploy --broadcast --rpc-url http://192.168.0.151:7545/
```

`http://192.168.0.151:7545/` is my local Ganache test network.

Test with `call`:
```bash
cast call 0xdd1c00993f657db6ada0d5e41ea05e5e2ff550c0 "test()" --rpc-url http://192.168.0.151:7545/
```
and returned a single `0x`

My other contract in a different repository:
```solidity
...
contract MyContract is
    ERC721A,
    ...
{
    string private previewBaseURI = "...";
    address generatorContractAddress = ...;
    ...

    function tokenURI(uint256 tokenId)
        public
        view
        override
        returns (string memory)
    {
        // I'm going to call the `generateURI` function from the zipped contract and return it.
        return "...";
    }
}
```

**Comment by merklejerk** [comment]
Ahh, I think it's because it's on a local testnet so there won't be an instance of the shared (`Z`) runtime on it. `_getOrDeployZ()` does deploy the runtime if it doesn't exist but it isn't preceded by a `vm.broadcast()`, so it doesn't get permanently deployed to your local testnet.  You can try adding a `vm.broadcast()` before it or just use a single `vm.startBroadcast()` at the start of the function.

**Comment by Cyanoure** [comment]
Thank you so much!
I'm calling it with the 'hack' above, but it didn't return the value that I expected.
With a little modification it works.
I replaced `delegatecall` to `call` method as like in the deployed wrapper example, now it works fine.

However, can I call it from another function?

Like this:
```solidity
function generateJSONURI(string memory _previewBaseURI, uint256 _tokenId, bool _someProperty) public view returns (string memory) {
    __forwardToZipped();
}

function __forwardToZipped() private view {
    function () fwd = __forwardToZippedNonView;
    function () view vfwd;
    assembly ("memory-safe") { vfwd := fwd }
    vfwd();
}

function  __forwardToZippedNonView() private {
    address zipped = zippedContractAddress;
    assembly ("memory-safe") {
        calldatacopy(0x00, 0x00, calldatasize())
        let s := call(gas(), zipped, callvalue(), 0x00, calldatasize(), 0x00, 0x00)
        returndatacopy(0x00, 0x00, returndatasize())
        if iszero(s) {
            revert(0x00, returndatasize())
        }
        return(0x00, returndatasize())
    }
}

function tokenURI(uint256 tokenId)
    public
    view
    override
    returns (string memory)
{
    if (!_exists(tokenId)) revert URIQueryForNonexistentToken();
    ...
    return generateJSONURI(previewBaseURI, tokenId, someProperty);
}
```

Because there is an extra boolean property of the NFTs that the zipped contract doesn't know about, only when we tell it through the function.

**Comment by merklejerk** [comment]
You can try something like this (assuming the target function is also called `generateJSON` on the zipped contract):

```solidity
function generateJSONURI(string memory _previewBaseURI, uint256 _tokenId, bool _someProperty) public view returns (string memory) {
    __forwardToZipped(abi.encodeCall(this.generateJSONURI, (_previewBaseURI, _tokenId, _someProperty)));
}

function __forwardToZipped(bytes memory callData) private view {
    function (bytes memory) fwd = __forwardToZippedNonView;
    function (bytes memory) view vfwd;
    assembly ("memory-safe") { vfwd := fwd }
    vfwd(callData);
}

function  __forwardToZippedNonView(bytes memory callData) private {
    address zipped = zippedContractAddress;
    assembly ("memory-safe") {
        let s := call(gas(), zipped, callvalue(), add(0x20, callData), mload(callData), 0x00, 0x00)
        returndatacopy(0x00, 0x00, returndatasize())
        if iszero(s) {
            revert(0x00, returndatasize())
        }
        return(0x00, returndatasize())
    }
}

function tokenURI(uint256 tokenId)
    public
    view
    override
    returns (string memory)
{
    if (!_exists(tokenId)) revert URIQueryForNonexistentToken();
    ...
    return generateJSONURI(previewBaseURI, tokenId, someProperty);
}
```

**Comment by Cyanoure** [comment]
Thank you so much!
Finally it's working. :D
